title: "BioMama - The Storyteller"
description: "Data analysis lover, mom, and storyteller. Join me on my journey."
remote_theme: pages-themes/dinky@v0.2.0
# show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one